const colors = {
  white: '#FFFFFF',
  majorelleBlue: '#525BDC',
  beauBlue: '#BFD7EA',
  asparagus: '#7CAE7A',
  smokyBlack: '#100B00',
  tyrianPurple: '#6A0F49',
};

export default {
  background: colors.white,
  text: colors.smokyBlack,
  navBarBackground: colors.majorelleBlue,
  navBarTitle: colors.white,
  navTabBackground: '',
  navTabIcon: '',
  cinemaListItemBackground: colors.white,
  cinemaListSeperator: colors.beauBlue,
  cinemaListItemTitle: colors.smokyBlack,
  cinemaListItemUrlButton: colors.tyrianPurple,
  cinemaListItemUrl: colors.white,
  cinemaButtons: colors.white,
  cinemaButtonText: colors.tyrianPurple,
  movieItemGradient: colors.beauBlue,
  movieItemGenre: colors.white,
  movieItemGenreText: colors.smokyBlack,
  movieLabel: colors.smokyBlack,
  movieInfo: colors.tyrianPurple,
  buyTicketButton: colors.asparagus,
  buyTicketButtonText: colors.white,
};
