const colors = {
  white: '#DCDCDC',
  majorelleBlue: '#525BDC',
  beauBlue: '#BFD7EA',
  asparagus: '#15A33B',
  smokyBlack: '#100B00',
  tyrianPurple: '#6A0F49',
};

export default {
  background: colors.white,
  text: colors.smokyBlack,
  navBarBackground: colors.majorelleBlue,
  navBarTitle: colors.white,
  navTabBackground: '',
  navTabIcon: '',
  cinemaListItemBackground: colors.white,
  cinemaListSeperator: colors.beauBlue,
  cinemaListItemTitle: colors.smokyBlack,
  cinemaListItemUrlButton: colors.tyrianPurple,
  cinemaListItemUrl: colors.white,
  cinemaButtons: colors.white,
  cinemaButtonText: colors.tyrianPurple,
  cinemaAddress: colors.tyrianPurple,
  cinemaAddressIcon: colors.tyrianPurple,
  movieItemGradient: colors.beauBlue,
  movieItemGenre: colors.white,
  movieItemGenreText: colors.smokyBlack,
  movieLabel: colors.smokyBlack,
  movieInfo: colors.majorelleBlue,
  buyTicketButton: colors.asparagus,
  buyTicketButtonText: colors.white,
  modalBackground: colors.beauBlue,
  modalCloseButton: colors.tyrianPurple,
  playTrailerButton: colors.majorelleBlue,
};
